### ISSUE TITLE
there are memory leak with current_trace_spans.

### ISSUE THREAD

**Issue by lixuzhena** [DataDog/pg_tracing#15]
### Environment details (Operating System, PostgreSQL version, pg_tracing version, etc)
- PostgreSQL version: 16.2
- pg_tracing version:latest
- Operating System:centos 7

### Steps to reproduce the issue

1.when the trace complete with a sql command, max_nested_level will be  -1 again.
2.when max_nested_level is -1, current_trace_spans will malloc again.
3.but current_trace_spans only malloc, not free.

### Describe the results you received
memory leak in every trace.

### Describe the results you expected
memory leak in every trace.

**Comment by bonnefoa** [comment]
`current_trace_spans` is allocated using [palloc](https://github.com/postgres/postgres/blob/master/src/include/utils/palloc.h) which relies on PostgreSQL's allocator. 
Allocations are done within `pg_tracing_mem_ctx` memory context. This context is reset during [cleanup_tracing](https://github.com/DataDog/pg_tracing/blob/43a30fc8a72dbe731979ef9ac19bc4ad5fa193c8/src/pg_tracing.c#L1137), freeing all allocations done for the trace. 

So unless I missed something, I haven't been able to reproduce a memory leak. Checking with `MemoryContextStats(pg_tracing_mem_ctx);`, the amount of memory used by the context is stable on a backend process generating traces with every query.
```
pg_tracing memory context: 25856 total in 3 blocks; 8680 free (5 chunks); 17176 used
Grand total: 25856 bytes in 3 blocks; 8680 free (5 chunks); 17176 used
...
pg_tracing memory context: 25856 total in 3 blocks; 8680 free (5 chunks); 17176 used
Grand total: 25856 bytes in 3 blocks; 8680 free (5 chunks); 17176 used
```

**Comment by bonnefoa** [comment]
It turns out there was one leak, though it's not on `current_trace_spans`. 
The query file is loaded in a malloced buffer that was never freed. I've fixed the issue in https://github.com/DataDog/pg_tracing/commit/eca9c9c8be3778e224e3eb10c5780f43a21d96ed
