### ISSUE TITLE
Make the service name configurable

### ISSUE THREAD

**Issue by viktara** [DataDog/pg_tracing#45]
I was looking for a way to do this and came across:
https://github.com/DataDog/pg_tracing/blob/e9cc2d0cd19d8b7b4e72a87cabb1fb4b45936f0c/src/pg_tracing_json.c#L139

Has anyone implemented this yet, I had a stab at it, but didn't quite get it to work.

**Comment by bonnefoa** [comment]
I've implemented this in #46. The service name is now configurable through a GUC variable at server start.
