### ISSUE TITLE
Question: why was this withdrawn from postgres commitfest?

### ISSUE THREAD

**Issue by achanda** [DataDog/pg_tracing#64]
Thank you for your work on this. I noticed that this was withdrawn from commitfest https://commitfest.postgresql.org/48/4456/ and I was curious why? The latest emails etc do not seem to have any information.

**Comment by bonnefoa** [comment]
Hi,

I've withdrawn the commitfest entry for multiple reason:
- I had multiple ongoing PG patches, some related to pg_tracing (adding extended protocol support for psql, missing query id tracking), other were just bugfix. Each patch usually have a big context switch cost so I'm trying to keep it to a manageable level.
- Lower the toil for the commitfest manager. From the latest discussions, creating this as an extension made more sense to have more flexibility and stabilise the architecture and features. There's still some improvements related to memory footprints and additional simplification that I need to tackle. Keeping this in the commitfest didn't make sense if the code was drifting from what was developed in github.

That being said, I wanted to push an update to the mail thread to advertise the move of the development to Github but that fell through the cracks. I also plan to release a first version soonish to start using it internally on non production workload.

**Comment by achanda** [comment]
Thanks, makes sense to me.
